package me.akhsaul.common.enums

enum class ResponseStatus(val code: Int) {
    HTTP_OK(200),
    HTTP_PARTIAL_CONTENT(206),
    HTTP_MOVED_PERMANENTLY(301),
    HTTP_FOUND(302),
    HTTP_SEE_OTHER(303),
    HTTP_BAD_REQUEST(400),
    HTTP_UNAUTHORIZED(401),
    HTTP_FORBIDDEN(403),
    HTTP_NOT_FOUND(404),
    HTTP_METHOD_NOT_ALLOWED(405),
    HTTP_NOT_ACCEPTABLE(406),
    HTTP_REQUEST_TIMEOUT(408),
    HTTP_TOO_MANY_REQUEST(429),
    HTTP_INTERNAL_SERVER_ERROR(500),
    HTTP_NOT_IMPLEMENTED(501),
    HTTP_BAD_GATEWAY(502),
    HTTP_SERVICE_UNAVAILABLE(503),
    HTTP_GATEWAY_TIMEOUT(504)
}